"""updated region code length

Revision ID: 03c659c73677
Revises: 9846a449b7e1
Create Date: 2023-01-31 22:24:12.798641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03c659c73677'
down_revision = '9846a449b7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipinfo', 'country_iso',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               type_=sa.String(length=3),
               existing_nullable=True)
    op.alter_column('ipinfo', 'region_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               type_=sa.String(length=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipinfo', 'region_code',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               existing_nullable=True)
    op.alter_column('ipinfo', 'country_iso',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               existing_nullable=True)
    # ### end Alembic commands ###
