"""empty message

Revision ID: 131a6de9157f
Revises: f0d028e6204c
Create Date: 2023-03-15 00:13:38.293244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '131a6de9157f'
down_revision = 'f0d028e6204c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('profile_requests', 'last_autocomplete_date',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_requests', 'last_autocomplete_date',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.drop_column('profile_requests', 'deleted_at')
    # ### end Alembic commands ###
