"""Added auto is_storie

Revision ID: 1bbc5e6ae8af
Revises: 032f437e3b38
Create Date: 2022-10-12 22:13:52.247473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbc5e6ae8af'
down_revision = '7bc5da89e677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_parsing_posts', sa.Column('is_storie', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_parsing_posts', 'is_storie')
    # ### end Alembic commands ###
