"""profile requests

Revision ID: 268b28b947fe
Revises: ca113ae6d5a8
Create Date: 2023-02-25 00:51:18.416209

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = '268b28b947fe'
down_revision = 'ca113ae6d5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    profile_occupation = op.create_table('profile_occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_occupations_id'), 'profile_occupations', ['id'], unique=False)
    op.create_table('profile_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_link', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('country_of_origin_code', sa.String(length=3), nullable=True),
    sa.Column('country_of_residence_code', sa.String(length=3), nullable=True),
    sa.Column('occupation', sa.String(length=64), nullable=True),
    sa.Column('last_autocomplete_date', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=expression.true()),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_requests_id'), 'profile_requests', ['id'], unique=False)
    op.create_table('profile_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_addresses_id'), 'profile_addresses', ['id'], unique=False)
    op.create_table('profile_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_emails_id'), 'profile_emails', ['id'], unique=False)
    profile_languages = op.create_table('profile_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_languages_id'), 'profile_languages', ['id'], unique=False)
    op.create_table('profile_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('smm_slug', sa.String(length=255), nullable=True),
    sa.Column('is_associative', sa.Boolean(), nullable=False, server_default=expression.false()),
    sa.Column('link_type', mysql.ENUM('WEB', 'SOCIAL', 'YOUTUBE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_links_id'), 'profile_links', ['id'], unique=False)
    profile_messengers = op.create_table('profile_messengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.Column('messenger_name', sa.String(length=255), nullable=False),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_messengers_id'), 'profile_messengers', ['id'], unique=False)
    op.create_table('profile_nicknames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_nicknames_id'), 'profile_nicknames', ['id'], unique=False)
    op.create_table('profile_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=True),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_phones_id'), 'profile_phones', ['id'], unique=False)
    # ### end Alembic commands ###
    # op.bulk_insert(profile_messengers, [
    #     {"id": 1, "name": "WhatsApp"},
    #     {"id": 2, "name": "Viber"},
    #     {"id": 3, "name": "Facebook Messenger"},
    #     {"id": 4, "name": "Telegram"},
    #     {"id": 5, "name": "Discord"},
    #     {"id": 6, "name": "Skype"},
    #     {"id": 7, "name": "Hangouts Google"},
    #     {"id": 8, "name": "Mail.ru Agent"},
    #     {"id": 9, "name": "Tencent QQ"},
    #     {"id": 10, "name": "WeChat"},
    #     {"id": 11, "name": "Snapchat"},
    #     {"id": 12, "name": "iMessage"},
    #     {"id": 13, "name": "Line"},
    #     {"id": 14, "name": "Signal"},
    #     {"id": 15, "name": "MTC Connect"},
    #     {"id": 16, "name": "TamTam"},
    #     {"id": 17, "name": "Yandex.Messenger"},
    #     {"id": 18, "name": "Bip"},
    #     {"id": 19, "name": "Imo.im"},
    # ], multiinsert=False)

    # op.bulk_insert(profile_languages, [
    #     {"id":1,"name":"Arabic","language_code":"ar"},
    #     {"id":2,"name":"Bengali","language_code":"bn"},
    #     {"id":3,"name":"English(UK)","language_code":"en-GB"},
    #     {"id":4,"name":"Portuguese","language_code":"pt-BR"},
    #     {"id":5,"name":"Bulgarian","language_code":"bg"},
    #     {"id":6,"name":"English(US)","language_code":"en"},
    #     {"id":7,"name":"German","language_code":"de"},
    #     {"id":8,"name":"Hindi","language_code":"hi"},
    #     {"id":9,"name":"Japanese","language_code":"ja"},
    #     {"id":10,"name":"Portuguese(Portugal)","language_code":"pt"},
    #     {"id":11,"name":"Russian","language_code":"ru"},
    #     {"id":12,"name":"Chinese","language_code":"zh"},
    #     {"id":13,"name":"Italian","language_code":"it"},
    #     {"id":14,"name":"Spanish","language_code":"es"},
    #     {"id":15,"name":"French","language_code":"fr"},
    #     {"id":16,"name":"Kannada","language_code":"kn"},
    #     {"id":17,"name":"Polish","language_code":"pl"},
    #     {"id":18,"name":"Thai","language_code":"th"},
    #     {"id":19,"name":"Chinese(Taiwan)","language_code":"zh-TW"},
    #     {"id":20,"name":"Tamil","language_code":"ta"},
    #     {"id":21,"name":"Telugu","language_code":"te"},
    #     {"id":22,"name":"Turkish","language_code":"tr"},
    #     {"id":23,"name":"Urdu","language_code":"ur"},
    #     {"id":24,"name":"Ukrainian","language_code":"uk"},
    #     {"id":25,"name":"Korean","language_code":"ko"},
    #     {"id":26,"name":"Vietnamese","language_code":"vi"},
    #     {"id":27,"name":"Marathi","language_code":"mr"},
    #     {"id":28,"name":"Gujarati","language_code":"gu"},
    #     {"id":29,"name":"Malayalam","language_code":"ml"},
    #     {"id":30,"name":"Estonian","language_code":"et"},
    #     {"id":31,"name":"Greek","language_code":"el"},
    #     {"id":32,"name":"Hungarian","language_code":"hu"},
    #     {"id":33,"name":"Icelandic","language_code":"is"},
    #     {"id":34,"name":"Indonesian","language_code":"id"},
    #     {"id":35,"name":"Latvian","language_code":"lv"},
    #     {"id":36,"name":"Lithuanian","language_code":"lt"},
    #     {"id":37,"name":"Malay","language_code":"ms"},
    #     {"id":38,"name":"Norwegian","language_code":"no"},
    #     {"id":39,"name":"Serbian","language_code":"sr"},
    #     {"id":40,"name":"Slovak","language_code":"sk"},
    #     {"id":41,"name":"Slovenian","language_code":"sl"},
    #     {"id":42,"name":"Swahili","language_code":"sw"},
    #     {"id":43,"name":"Swedish","language_code":"se"},
    #     {"id":44,"name":"Hebrew","language_code":"he"},
    #     {"id":45,"name":"Dutch","language_code":"nl"}
    # ], multiinsert=False)

    # op.bulk_insert(profile_occupation, [
    #     {"id":1,"name":"Personal","slug":"personal"},
    #     {"id":2,"name":"Journalist","slug":"journalist"},
    #     {"id":3,"name":"Politician","slug":"politician"},
    #     {"id":4,"name":"Activist","slug":"activist"},
    #     {"id":5,"name":"Influencer","slug":"influencer"},
    #     {"id":6,"name":"Blogger","slug":"blogger"},
    #     {"id":7,"name":"Minister","slug":"minister"},
    #     {"id":8,"name":"Government Official", "slug":"government_official"},
    #     {"id":9,"name":"Professor","slug":"professor"},
    #     {"id":10,"name":"Author","slug":"author"},
    #     {"id":11,"name":"Lawyer","slug":"lawyer"},
    # ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_phones_id'), table_name='profile_phones')
    op.drop_table('profile_phones')
    op.drop_index(op.f('ix_profile_nicknames_id'), table_name='profile_nicknames')
    op.drop_table('profile_nicknames')
    op.drop_index(op.f('ix_profile_messengers_id'), table_name='profile_messengers')
    op.drop_table('profile_messengers')
    op.drop_index(op.f('ix_profile_links_id'), table_name='profile_links')
    op.drop_table('profile_links')
    op.drop_index(op.f('ix_profile_languages_id'), table_name='profile_languages')
    op.drop_table('profile_languages')
    op.drop_index(op.f('ix_profile_emails_id'), table_name='profile_emails')
    op.drop_table('profile_emails')
    op.drop_index(op.f('ix_profile_addresses_id'), table_name='profile_addresses')
    op.drop_table('profile_addresses')
    op.drop_index(op.f('ix_profile_requests_id'), table_name='profile_requests')
    op.drop_table('profile_requests')
    op.drop_index(op.f('ix_profile_occupations_id'), table_name='profile_occupations')
    op.drop_table('profile_occupations')
    # ### end Alembic commands ###
