"""Added proxy and ipinfo tables

Revision ID: 4a5b798edbe1
Revises: 1bbc5e6ae8af
Create Date: 2022-11-03 10:09:08.132058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a5b798edbe1'
down_revision = '1bbc5e6ae8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipinfo',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('country_iso', sa.String(length=2), nullable=True),
    sa.Column('region_name', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('asn', sa.String(length=32), nullable=True),
    sa.Column('asn_org', sa.String(length=64), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipinfo_ip'), 'ipinfo', ['ip'], unique=True)
    op.create_table('proxies',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('is_v6', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_https', sa.Boolean(), nullable=False),
    sa.Column('is_socks', sa.Boolean(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_residential', sa.Boolean(), nullable=False),
    sa.Column('is_datacenter', sa.Boolean(), nullable=False),
    sa.Column('is_mobile', sa.Boolean(), nullable=False),
    sa.Column('latency', mysql.FLOAT(unsigned=True), nullable=False),
    sa.Column('stability', mysql.FLOAT(unsigned=True), nullable=False),
    sa.Column('attempts', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('https_attempts', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_ip'), 'proxies', ['ip'], unique=False)
    op.create_index(op.f('ix_proxies_port'), 'proxies', ['port'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxies_port'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_ip'), table_name='proxies')
    op.drop_table('proxies')
    op.drop_index(op.f('ix_ipinfo_ip'), table_name='ipinfo')
    op.drop_table('ipinfo')
    # ### end Alembic commands ###
