"""social_account note field

Revision ID: 503454633d42
Revises: 03c659c73677
Create Date: 2023-02-01 12:05:55.409745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503454633d42'
down_revision = '03c659c73677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'note')
    # ### end Alembic commands ###
