"""empty message

Revision ID: 599b6c9e958e
Revises: a40b09cc38f5
Create Date: 2023-03-16 21:58:08.168860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599b6c9e958e'
down_revision = 'a40b09cc38f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
