"""Added social tables

Revision ID: 7bc5da89e677
Revises: d4867f3a4c0a
Create Date: 2022-09-18 17:41:06.635540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bc5da89e677'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_parsing_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('social_request_id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('smm_id', sa.Integer(), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_login', sa.String(length=255), nullable=True),
    sa.Column('post_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.Column('featured_image', sa.Text(), nullable=True),
    sa.Column('video_image', sa.Text(), nullable=True),
    sa.Column('source_link', sa.Text(), nullable=True),
    sa.Column('is_updated', sa.Boolean(), nullable=False),
    sa.Column('crawler_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_news', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_parsing_posts_id'), 'social_parsing_posts', ['id'], unique=False)
    op.create_table('social_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_global_search', sa.Boolean(), nullable=False),
    sa.Column('reply_link', sa.String(length=255), nullable=False),
    sa.Column('crawling_frequency', sa.Integer(), nullable=False),
    sa.Column('crawling_start_date', sa.DateTime(), nullable=False),
    sa.Column('crawling_end_date', sa.DateTime(), nullable=False),
    sa.Column('crawling_last_run_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_requests_id'), 'social_requests', ['id'], unique=False)
    op.create_table('social_hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('social_request_id', sa.Integer(), nullable=False),
    sa.Column('smm_engine_id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=7), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('error_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_request_id'], ['social_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_hashtags_id'), 'social_hashtags', ['id'], unique=False)
    op.create_table('social_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('social_request_id', sa.Integer(), nullable=False),
    sa.Column('smm_engine_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=7), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('error_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_request_id'], ['social_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_keywords_id'), 'social_keywords', ['id'], unique=False)
    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('social_request_id', sa.Integer(), nullable=False),
    sa.Column('smm_engine_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(length=1000), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('error_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_request_id'], ['social_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_links_id'), 'social_links', ['id'], unique=False)
    op.create_table('social_posts_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('social_parsing_post_id', sa.Integer(), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_parsing_post_id'], ['social_parsing_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_attachments_id'), 'social_posts_attachments', ['id'], unique=False)
    op.create_table('social_posts_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('social_parsing_post_id', sa.Integer(), nullable=True),
    sa.Column('reaction', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_parsing_post_id'], ['social_parsing_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_reactions_id'), 'social_posts_reactions', ['id'], unique=False)
    op.create_table('social_posts_requests',
    sa.Column('social_request_id', sa.Integer(), nullable=False),
    sa.Column('social_parsing_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['social_parsing_post_id'], ['social_parsing_posts.id'], ),
    sa.ForeignKeyConstraint(['social_request_id'], ['social_requests.id'], ),
    sa.PrimaryKeyConstraint('social_request_id', 'social_parsing_post_id')
    )
    op.create_table('social_posts_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('social_parsing_post_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_parsing_post_id'], ['social_parsing_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_stats_id'), 'social_posts_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_posts_stats_id'), table_name='social_posts_stats')
    op.drop_table('social_posts_stats')
    op.drop_table('social_posts_requests')
    op.drop_index(op.f('ix_social_posts_reactions_id'), table_name='social_posts_reactions')
    op.drop_table('social_posts_reactions')
    op.drop_index(op.f('ix_social_posts_attachments_id'), table_name='social_posts_attachments')
    op.drop_table('social_posts_attachments')
    op.drop_index(op.f('ix_social_links_id'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_index(op.f('ix_social_keywords_id'), table_name='social_keywords')
    op.drop_table('social_keywords')
    op.drop_index(op.f('ix_social_hashtags_id'), table_name='social_hashtags')
    op.drop_table('social_hashtags')
    op.drop_index(op.f('ix_social_requests_id'), table_name='social_requests')
    op.drop_table('social_requests')
    op.drop_index(op.f('ix_social_parsing_posts_id'), table_name='social_parsing_posts')
    op.drop_table('social_parsing_posts')
    # ### end Alembic commands ###
