"""Updated cookie model

Revision ID: 84b6625abc55
Revises: e1c1feaef5f9
Create Date: 2023-01-12 23:18:10.194886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b6625abc55'
down_revision = 'e1c1feaef5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookies', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.add_column('cookies', sa.Column('date_locked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookies', 'date_locked')
    op.drop_column('cookies', 'is_locked')
    # ### end Alembic commands ###
