"""user-agent

Revision ID: 9846a449b7e1
Revises: 84b6625abc55
Create Date: 2023-01-31 20:09:14.454505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9846a449b7e1'
down_revision = '84b6625abc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('user_agent', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'user_agent')
    # ### end Alembic commands ###
