"""empty message

Revision ID: b5aecb8cc782
Revises: 131a6de9157f
Create Date: 2023-03-16 21:25:24.836061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5aecb8cc782'
down_revision = '131a6de9157f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_addresses_ibfk_1', 'profile_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'profile_addresses', 'profile_requests', ['profile_request_id'], ['id'], ondelete='cascade')
    op.drop_constraint('profile_emails_ibfk_1', 'profile_emails', type_='foreignkey')
    op.create_foreign_key(None, 'profile_emails', 'profile_requests', ['profile_request_id'], ['id'], ondelete='cascade')
    op.drop_constraint('profile_languages_ibfk_1', 'profile_languages', type_='foreignkey')
    op.create_foreign_key(None, 'profile_languages', 'profile_requests', ['profile_request_id'], ['id'], ondelete='cascade')
    op.drop_constraint('profile_messengers_ibfk_1', 'profile_messengers', type_='foreignkey')
    op.create_foreign_key(None, 'profile_messengers', 'profile_requests', ['profile_request_id'], ['id'], ondelete='cascade')
    op.drop_constraint('profile_nicknames_ibfk_1', 'profile_nicknames', type_='foreignkey')
    op.create_foreign_key(None, 'profile_nicknames', 'profile_requests', ['profile_request_id'], ['id'], ondelete='cascade')
    op.drop_constraint('profile_phones_ibfk_1', 'profile_phones', type_='foreignkey')
    op.create_foreign_key(None, 'profile_phones', 'profile_requests', ['profile_request_id'], ['id'], ondelete='cascade')
    op.drop_constraint('profile_requests_links_ibfk_2', 'profile_requests_links', type_='foreignkey')
    op.drop_constraint('profile_requests_links_ibfk_1', 'profile_requests_links', type_='foreignkey')
    op.create_foreign_key(None, 'profile_requests_links', 'profile_requests', ['profile_request_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'profile_requests_links', 'profile_links', ['profile_link_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_requests_links', type_='foreignkey')
    op.drop_constraint(None, 'profile_requests_links', type_='foreignkey')
    op.create_foreign_key('profile_requests_links_ibfk_1', 'profile_requests_links', 'profile_links', ['profile_link_id'], ['id'])
    op.create_foreign_key('profile_requests_links_ibfk_2', 'profile_requests_links', 'profile_requests', ['profile_request_id'], ['id'])
    op.drop_constraint(None, 'profile_phones', type_='foreignkey')
    op.create_foreign_key('profile_phones_ibfk_1', 'profile_phones', 'profile_requests', ['profile_request_id'], ['id'])
    op.drop_constraint(None, 'profile_nicknames', type_='foreignkey')
    op.create_foreign_key('profile_nicknames_ibfk_1', 'profile_nicknames', 'profile_requests', ['profile_request_id'], ['id'])
    op.drop_constraint(None, 'profile_messengers', type_='foreignkey')
    op.create_foreign_key('profile_messengers_ibfk_1', 'profile_messengers', 'profile_requests', ['profile_request_id'], ['id'])
    op.drop_constraint(None, 'profile_languages', type_='foreignkey')
    op.create_foreign_key('profile_languages_ibfk_1', 'profile_languages', 'profile_requests', ['profile_request_id'], ['id'])
    op.drop_constraint(None, 'profile_emails', type_='foreignkey')
    op.create_foreign_key('profile_emails_ibfk_1', 'profile_emails', 'profile_requests', ['profile_request_id'], ['id'])
    op.drop_constraint(None, 'profile_addresses', type_='foreignkey')
    op.create_foreign_key('profile_addresses_ibfk_1', 'profile_addresses', 'profile_requests', ['profile_request_id'], ['id'])
    # ### end Alembic commands ###
