"""added email_password

Revision ID: ca113ae6d5a8
Revises: 503454633d42
Create Date: 2023-02-01 19:35:44.749396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca113ae6d5a8'
down_revision = '503454633d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('email_password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'email_password')
    # ### end Alembic commands ###
