"""Added social_accounts and cookies tables

Revision ID: e1c1feaef5f9
Revises: 4a5b798edbe1
Create Date: 2022-11-03 12:06:14.944666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1c1feaef5f9'
down_revision = '4a5b798edbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('smm_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', mysql.ENUM('M', 'F', 'O'), nullable=True),
    sa.Column('country_iso', sa.String(length=2), nullable=True),
    sa.Column('language_iso', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_twofactor', sa.Boolean(), nullable=False),
    sa.Column('twofactor_token', sa.String(length=255), nullable=True),
    sa.Column('twofactor_recovery_codes', sa.String(length=255), nullable=True),
    sa.Column('bans_count', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('captcha_count', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('quality_percent', mysql.FLOAT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cookies',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cookies_file', sa.String(length=255), nullable=False),
    sa.Column('account_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('proxy_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookies')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
