"""empty message

Revision ID: f0d028e6204c
Revises: 268b28b947fe
Create Date: 2023-03-02 10:37:29.351374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0d028e6204c'
down_revision = '268b28b947fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('smm_slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_links_id'), 'profile_links', ['id'], unique=False)
    op.create_table('profile_occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_occupations_id'), 'profile_occupations', ['id'], unique=False)
    op.create_table('profile_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_link', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('country_of_origin_code', sa.String(length=3), nullable=True),
    sa.Column('country_of_residence_code', sa.String(length=3), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('last_autocomplete_date', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_requests_id'), 'profile_requests', ['id'], unique=False)
    op.create_table('profile_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_addresses_id'), 'profile_addresses', ['id'], unique=False)
    op.create_table('profile_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_emails_id'), 'profile_emails', ['id'], unique=False)
    op.create_table('profile_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_languages_id'), 'profile_languages', ['id'], unique=False)
    op.create_table('profile_messengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.Column('messenger_name', sa.String(length=255), nullable=False),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_messengers_id'), 'profile_messengers', ['id'], unique=False)
    op.create_table('profile_nicknames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_nicknames_id'), 'profile_nicknames', ['id'], unique=False)
    op.create_table('profile_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=True),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_phones_id'), 'profile_phones', ['id'], unique=False)
    op.create_table('profile_requests_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_request_id', sa.Integer(), nullable=False),
    sa.Column('profile_link_id', sa.Integer(), nullable=False),
    sa.Column('is_associative', sa.Boolean(), nullable=False),
    sa.Column('link_type', mysql.ENUM('WEB', 'SOCIAL', 'YOUTUBE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_link_id'], ['profile_links.id'], ),
    sa.ForeignKeyConstraint(['profile_request_id'], ['profile_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_requests_links_id'), 'profile_requests_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_requests_links_id'), table_name='profile_requests_links')
    op.drop_table('profile_requests_links')
    op.drop_index(op.f('ix_profile_phones_id'), table_name='profile_phones')
    op.drop_table('profile_phones')
    op.drop_index(op.f('ix_profile_nicknames_id'), table_name='profile_nicknames')
    op.drop_table('profile_nicknames')
    op.drop_index(op.f('ix_profile_messengers_id'), table_name='profile_messengers')
    op.drop_table('profile_messengers')
    op.drop_index(op.f('ix_profile_languages_id'), table_name='profile_languages')
    op.drop_table('profile_languages')
    op.drop_index(op.f('ix_profile_emails_id'), table_name='profile_emails')
    op.drop_table('profile_emails')
    op.drop_index(op.f('ix_profile_addresses_id'), table_name='profile_addresses')
    op.drop_table('profile_addresses')
    op.drop_index(op.f('ix_profile_requests_id'), table_name='profile_requests')
    op.drop_table('profile_requests')
    op.drop_index(op.f('ix_profile_occupations_id'), table_name='profile_occupations')
    op.drop_table('profile_occupations')
    op.drop_index(op.f('ix_profile_links_id'), table_name='profile_links')
    op.drop_table('profile_links')
    # ### end Alembic commands ###
